### ISSUE TITLE
Aries patches v3

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#27]
Nodes and defconfig changes for:
- fmradio for galaxys
- touchkeys
- s6e63m0 panel
- bma150
- gp2a
- fsa9480
- max8998 charger

Branch **for-upstream/aries-patches-v3**

TODO: need to wait till all other patches are applied (moved from linux-next).

**Comment by PabloPL** [comment]
v2 patches are merged into stable. Now we can cleanup/remove old branches.

**Comment by kwizart** [comment]
Seems like I have overwritten my last known working dtb with this branch dtb and I cannot boot anymore. (no display after "booting kernel" using u-boot).
I'm using a kernel 5.0.0 from this earlier branch.
Is there anything missing ? Also It seems hard to fetch various branches because there is a need to fix some conflicts between some of them...

I've tried to enable some debug console, but no luck. the crash seems to occurs with a previously known working kernel and current 5.4-rc4 kernel with this branches dtb. (on galaxys).
(the same rootfs is booting fine on another arm device).

**Comment by xc-racer99** [comment]
No working display is probably due to a mismatch in DTB/kernel - depending on when you fetched the branch, it may have slightly different parameters for the s6e63m0 as the bindings underwent a few revisions before they were accepted upstream.

I've personally never used the aries-patches-v3 - I always created my own patches when working on something.  Yes, it can be a pain to merge the defconfig/dts changes from the various branches - but this is really the only way to break up changes so they could be accepted upstream.

**Comment by xc-racer99** [comment]
s6e63m0, si4709, touhkeys, initial wm8994 (no machine driver), and fsa9480 have been submitted and are queued in krzk's for-next along with several misc fixes.

gp2a, max8998 charger, bma023 all need separate patches to their drivers still.
