### ISSUE TITLE
Submit minimal galaxys and galaxys4g dts files

### ISSUE THREAD

**Issue by PabloPL** [PabloPL/linux#4]

**Comment by PabloPL** [comment]
Got initial feedback. Preparing fixed version at for-upstream/aries-minimal-v2 branch.

**Comment by xc-racer99** [comment]
As in for LDO6?  Have a look at https://github.com/xc-racer99/android_kernel_samsung_aries/blob/aosp-7.1/arch/arm/mach-s5pv210/mach-aries.c#L564 for how its configured for the T959P (used by modem)

ESAFEOUT2, probably has to be deduced from drivers/power/s5pc110_battery.c

LDO10 I have no idea what it should default to...  I'll try and read the registers later today and determine what they are.

**Comment by xc-racer99** [comment]
Nope, not booting for me.  I'll try and find out which of the changes is causing the issue.

**Comment by PabloPL** [comment]
I've removed patches for broken bootloader. Without that, it's not working for me even if using uboot.
I would try with this at first.

**Comment by xc-racer99** [comment]
Yeah, its edaf7ab - I'm guessing it's because UART1 isn't initialized by u-boot while UART2 is.  I'll do some testing for that.

Can at least verify that this boots now

**Comment by PabloPL** [comment]
For me it wasn't able to detect sdcard. Most important difference between v1 and v2 is addition of max8998-pmic regulators and set irq type. Need to do more testing for this.
It's sad, that stock kernel don't have settings for all regulators.

**Comment by xc-racer99** [comment]
Yep, SD card wasn't detected for me either.

**Comment by xc-racer99** [comment]
Ok, based on stock kernel, ENVICHG is always enabled (dumped the registers and worked backwords).
LDO10 is inded 1.2V and always enabled

As well, sdcard worked just fine when voltages were removed from the ESAFEOUT regulators...
Note that since removing the console parameters from bootparams, I no longer get a serial console - it's just a framebuffer console.

**Comment by xc-racer99** [comment]
Alright, https://github.com/xc-racer99/linux/commit/d7447026780ed9394f3b25f0a3616b897b770366 is working for me for regulators.
https://github.com/xc-racer99/linux/commit/e893b1d233cd799ce453e644cbaee04808fce92f is so that there's still a console on UART2

Feel free to adjust/squish the commits into yours as desired.

**Comment by PabloPL** [comment]
@xc-racer99 Ok thanks, i'll do it (was bussy for few days) and submit patches again.

PS: Got unbrickable mod applied on my device.

**Comment by PabloPL** [comment]
Initial patches has been accepted and will be merged soon into mainline.
This issue can be closed.

**Comment by PabloPL** [comment]
@xc-racer99 
Maybe we could skip for now yas529 sensor and focus now for example on LCD/audio (it would make this device more usefull) ?

**Comment by xc-racer99** [comment]
I've been working on audio as well, I have a building driver, but whenever I try to play something, it just hangs.  I think there's a clock that I'm not setting up properly, but I'm not sure...

**Comment by MYEUHD** [comment]
The initial patches have landed in Linus' tree!
